### ISSUE TITLE
How to calculate the Memory of models for the table in paper?

### ISSUE THREAD

**Issue by BoyOfChu** [xi-jia/LessNet#1]
How to calculate the Memory of models for the table in paper? Look forward to your answer, thank you

**Comment by xi-jia** [comment]
Memory in Fig 1 can be assessed by nvidia-smi
Memory in other tables and figures is measured by https://pypi.org/project/torchinfo/

**Comment by BoyOfChu** [comment]
Thank you very much. I have calculated the memory of VoxelMorph_1 via torchinfo. The values of "Total params" and "Total mult-adds (G)" are same as Table.7. However the value of "Estimated Total Size (MB)" is 3201.75 MB, which is bigger than "2999.88". I'm not sure what went wrong.

model = VxmDense_1((160,192,224))
summary(model, input_size=[(1, 2, 160, 192, 224)], device='cuda')

**Comment by xi-jia** [comment]
What I reported is the Forward/backward pass size (MB), if your Forward/backward pass size (MB) is still different from the value I reported, I guess it might be because of different hardwares / software versions.

**Comment by BoyOfChu** [comment]
Thank you very much!
